### ISSUE TITLE
mvn tests fails

### ISSUE THREAD

**Issue by WolfgangFahl** [russgold/httpunit#5]
Results :

Tests in error: 
  testServletParameters(com.meterware.servletunit.ServletAccessTest): Error on HTTP request: 404 No servlet mapping defined [http://localhost/SimpleServlet]

Tests run: 823, Failures: 0, Errors: 1, Skipped: 8

**Comment by russgold** [comment]
Looks like a test ordering problem, meaning that the test wasn't being initialized correctly, but only worked because of other tests that had run before it.  You can confirm this by trying to run ServletAccessTest by itself - it will fail.

**Comment by russgold** [comment]
Found a change that seems relevant:

https://github.com/russgold/httpunit/commit/d0f843e3b5cb38f3db03995658ce6b585ed9cbd7
Fahl Sep 12, 2012 "add checks for InvocationContextFactory - clearly ServletAccessTest can not be run on it's own with this change"

It's not test ordering, precisely. ServletAccessTest is designed to be run only from JUnitServletTest. It should not be run directly from the maven build at all. The test ordering apparently allowed it to work, but it should not have been run.

**Comment by russgold** [comment]
Fixed with change 599c1157b0d5c98971f rename ServletAccessTest to avoid running it from Maven
